// <auto-generated />
using Final01Demo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Final01Demo.Migrations
{
    [DbContext(typeof(FinalDbContext))]
    [Migration("20240802123755_CreateV1")]
    partial class CreateV1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Final01Demo.Models.CanHo", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("DienTich")
                        .HasColumnType("float");

                    b.Property<string>("IDToaNha")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SoNha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("IDToaNha");

                    b.ToTable("canHos");
                });

            modelBuilder.Entity("Final01Demo.Models.ToaNha", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("toaNha");
                });

            modelBuilder.Entity("Final01Demo.Models.CanHo", b =>
                {
                    b.HasOne("Final01Demo.Models.ToaNha", "toaNha")
                        .WithMany("canHos")
                        .HasForeignKey("IDToaNha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("toaNha");
                });

            modelBuilder.Entity("Final01Demo.Models.ToaNha", b =>
                {
                    b.Navigation("canHos");
                });
#pragma warning restore 612, 618
        }
    }
}
